### ISSUE TITLE
Aliased method disapper on rspec-mocks 3.4.1

### ISSUE THREAD

**Issue by shigi** [rspec/rspec-mocks#1057]
```ruby
class A
  def g1
    1
  end
end

class B < A
  def f
    g2
  end

  alias g2 g1
end

describe '#f', order: true do
  let(:b) { B.new }

  it 'call B#g2' do
    expect_any_instance_of(B).to receive(:g2).with(no_args)
    b.f
  end

  it { expect(b.f).to eq 1 }
end
```

This works fine on rspec-mocks 3.4.0.
But on rspec-mocks 3.4.1, below error occurs.

```
Failures:

  1) #f 
     Failure/Error: g2

     NameError:
       undefined local variable or method `g2' for #<B:0x007fd11f2f15c8>
     # ./test_spec.rb:9:in `f'
     # ./test_spec.rb:23:in `block (2 levels) in <top (required)>'
```

The version of Ruby is 2.1.5 and 2.2.3.
