### ISSUE TITLE
Verifying double ignores custom matcher `failure_message`

### ISSUE THREAD

**Issue by dmolesUC3** [rspec/rspec-mocks#1086]
#### Steps to reproduce:

1. Create a custom matcher with a custom failure message, e.g.:

   ```ruby
   RSpec::Matchers.define :foo do
     match do |actual|
       actual.is_a?(Foo)
     end
   
     failure_message do |actual|
       return "Expected Foo, got #{actual.class}" unless actual.is_a(Foo)
     end
   end
   ```

2.  Use the custom matcher to verify a (failing) double invocation, e.g.:

   ```ruby
   RSpec.describe 'frob' do
     it 'frobs' do
       mock_frob = instance_double(Frob)
       expect(mock_frob).to receive(:frob).with(foo)
       mock_frob.frob('Baz')
     end
   end
   ```

#### Expected:

Test failure output includes custom message.

#### Actual:

Test failure output is generic:

```
Failures:

  1) frob frobs
     Failure/Error: mock_frob.frob('Baz')

       #<InstanceDouble(Frob) (anonymous)> received :frob with unexpected arguments
         expected: (foo)
              got: ("Baz")
```

#### Notes

Running the test in the debugger, it seems like `failure_message` registers the message block successfully, but then the block is never invoked.

This isn't a big deal for this simple use case, but for a complex custom matcher, especially one with chained arguments, it would be really useful to be able to describe in detail just what was expected of the argument and just what was wrong with it.

Using rspec-mocks 3.4.1.
