### ISSUE TITLE
error_generator using rspec-support differ without loading it

### ISSUE THREAD

**Issue by boutil** [rspec/rspec-mocks#1317]
### error_generator using rspec-support differ without loading it

Trying to run modified yard's specs with ruby 2.7, I encountered 2 failures, but the error message was pointing to a problem with rspec-mocks.

```
Failure/Error: expect(YARD::Config.options[:test]).to be true
     
     NameError:
       uninitialized constant RSpec::Support::Differ
     # /usr/lib/ruby/vendor_ruby/rspec/mocks/error_generator.rb
```

It seems that error_generator.rb uses rspec-support differ, without loading it explicitly. I was unable to trace a path that could lead to its loading.

This is pretty similar to the issue #893
Adding the line:
`Spec::Support.require_rspec_support "differ"`
at the top of the file, I was able to get a meaningful error for my specs.

### Your environment
* Ruby version: 2.7
* rspec-mocks version: 3.9.1

**Comment by JonRowe** [comment]
`/usr/lib/ruby/vendor_ruby/rspec/mocks/error_generator.rb` This is suspicious to me, this is not a normal gem installed path, are you sure you're using 3.9.1? As #893 fixed this by using autoload...

**Comment by boutil** [comment]
This trace has been obtained with the version indicated of rspec-mocks, packaged for Debian. This explains the unusual path. I installed the gem, and reproduced the issue with the installed gem, with ruby2.7, running `ruby2.7 -S rspec`:

```
Failures:

  1) YARD::Config.load overwrites options with data in ~/.yard/config
     Failure/Error: expect(YARD::Config.options[:test]).to be true
     
     NameError:
       uninitialized constant RSpec::Support::Differ
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/error_generator.rb:304:in `differ'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/error_generator.rb:288:in `diff_message'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/error_generator.rb:274:in `error_message'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/message_expectation.rb:506:in `raise_unexpected_message_args_error'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/proxy.rb:206:in `message_received'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/proxy.rb:345:in `message_received'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
     # /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:59:in `block (2 levels) in require'
     # /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:47:in `each'
     # /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:47:in `block in require'
     # /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:46:in `each'
     # /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:46:in `require'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/fail_with.rb:14:in `differ'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/fail_with.rb:33:in `fail_with'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/config_spec.rb:22:in `block (3 levels) in <top (required)>'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `instance_exec'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `block in run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `block in run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:612:in `block in run_around_example_hooks_for'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:345:in `call'
     # ./spec/spec_helper.rb:121:in `block (2 levels) in <top (required)>'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:450:in `instance_exec'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:450:in `instance_exec'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:381:in `execute_with'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:614:in `block (2 levels) in run_around_example_hooks_for'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:345:in `call'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:615:in `run_around_example_hooks_for'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:254:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `map'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `run_examples'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:595:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `block in run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `map'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `map'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:74:in `report'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:89:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/bin/rspec:4:in `<main>'
```

Adding the line as I propose in my initial message gives still a failing test, but with a meaningful trace:
```
1) YARD::Config.load overwrites options with data in ~/.yard/config
     Failure/Error: expect(YARD::Config.options[:test]).to be true
     
       expected true
            got nil
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-support-3.9.2/lib/rspec/support.rb:97:in `block in <module:Support>'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-support-3.9.2/lib/rspec/support.rb:106:in `notify_failure'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/config_spec.rb:22:in `block (3 levels) in <top (required)>'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `instance_exec'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `block in run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `block in run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:612:in `block in run_around_example_hooks_for'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:345:in `call'
     # ./spec/spec_helper.rb:121:in `block (2 levels) in <top (required)>'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:450:in `instance_exec'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:450:in `instance_exec'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:381:in `execute_with'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:614:in `block (2 levels) in run_around_example_hooks_for'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:345:in `call'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:615:in `run_around_example_hooks_for'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:254:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `map'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `run_examples'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:595:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `block in run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `map'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `map'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:74:in `report'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:89:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
     # /home/boutil/.gem/ruby/2.7.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/bin/rspec:4:in `<main>'
```
