### ISSUE TITLE
Test suite YAML issues

### ISSUE THREAD

**Issue by voxik** [rspec/rspec-mocks#174]
Hi,

I have issues to run rspec-mocks 2.11.2 test suite with Ruby 1.9.3:

```
  1) RSpec::Mocks::Serialization without YAML loaded does not add #to_yaml to the stubbed object
     Failure/Error: @orig_yaml_constant = Object.send(:remove_const, :YAML)
     NameError:
       constant Object::YAML not defined
     # /builddir/build/BUILD/rubygem-rspec-mocks-2.11.2/usr/share/gems/gems/rspec-mocks-2.11.2/spec/rspec/mocks/serialization_spec.rb:31:in `remove_const'
     # /builddir/build/BUILD/rubygem-rspec-mocks-2.11.2/usr/share/gems/gems/rspec-mocks-2.11.2/spec/rspec/mocks/serialization_spec.rb:31:in `block (2 levels) in without_yaml_loaded'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `run_in'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `block in run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:368:in `run_hook'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `block in run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:217:in `run_before_each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:79:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'
  2) RSpec::Mocks::Serialization with YAML loaded using Syck as the YAML engine behaves like normal YAML serialization serializes to yaml the same with and without stubbing, using #to_yaml
     Failure/Error: before(:each) { YAML::ENGINE.yamler = 'syck' }
     NameError:
       uninitialized constant RSpec::Mocks::ENGINE
     Shared Example Group: "normal YAML serialization" called from 
     # /builddir/build/BUILD/rubygem-rspec-mocks-2.11.2/usr/share/gems/gems/rspec-mocks-2.11.2/spec/rspec/mocks/serialization_spec.rb:76:in `block (4 levels) in <module:Mocks>'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `run_in'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `block in run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:368:in `run_hook'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `block in run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:217:in `run_before_each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:79:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'
  3) RSpec::Mocks::Serialization with YAML loaded using Syck as the YAML engine behaves like normal YAML serialization serializes to yaml the same with and without stubbing, using YAML.dump
     Failure/Error: before(:each) { YAML::ENGINE.yamler = 'syck' }
     NameError:
       uninitialized constant RSpec::Mocks::ENGINE
     Shared Example Group: "normal YAML serialization" called from 
     # /builddir/build/BUILD/rubygem-rspec-mocks-2.11.2/usr/share/gems/gems/rspec-mocks-2.11.2/spec/rspec/mocks/serialization_spec.rb:76:in `block (4 levels) in <module:Mocks>'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `run_in'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `block in run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:368:in `run_hook'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `block in run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:217:in `run_before_each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:79:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'
  4) RSpec::Mocks::Serialization with YAML loaded using Psych as the YAML engine behaves like normal YAML serialization serializes to yaml the same with and without stubbing, using #to_yaml
     Failure/Error: before(:each) { YAML::ENGINE.yamler = 'psych' }
     NameError:
       uninitialized constant RSpec::Mocks::ENGINE
     Shared Example Group: "normal YAML serialization" called from 
     # /builddir/build/BUILD/rubygem-rspec-mocks-2.11.2/usr/share/gems/gems/rspec-mocks-2.11.2/spec/rspec/mocks/serialization_spec.rb:81:in `block (4 levels) in <module:Mocks>'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `run_in'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `block in run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:368:in `run_hook'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `block in run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:217:in `run_before_each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:79:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'
  5) RSpec::Mocks::Serialization with YAML loaded using Psych as the YAML engine behaves like normal YAML serialization serializes to yaml the same with and without stubbing, using YAML.dump
     Failure/Error: before(:each) { YAML::ENGINE.yamler = 'psych' }
     NameError:
       uninitialized constant RSpec::Mocks::ENGINE
     Shared Example Group: "normal YAML serialization" called from 
     # /builddir/build/BUILD/rubygem-rspec-mocks-2.11.2/usr/share/gems/gems/rspec-mocks-2.11.2/spec/rspec/mocks/serialization_spec.rb:81:in `block (4 levels) in <module:Mocks>'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:35:in `run_in'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `block in run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:70:in `run_all'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/hooks.rb:368:in `run_hook'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `block in run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:292:in `run_before_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:217:in `run_before_each'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:79:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'
Finished in 0.26069 seconds
587 examples, 5 failures, 2 pending
```

using following command:

```
$ ruby -Ilib/ -S rspec spec/
```

These are gems I have installed on my system:

```
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.1.0)
diff-lcs (1.1.2)
io-console (0.3)
json (1.6.5)
rake (0.9.2.2)
rdoc (3.12)
rspec-core (2.8.0)
rspec-expectations (2.8.0)
rspec-mocks (2.8.0)
```

Any idea what is going wrong? Thank you
