### ISSUE TITLE
Double with attr_writer (=) causes "undefined method `matches_name_but_not_args'" error on 3.0.0.beta1

### ISSUE THREAD

**Issue by paulanthonywilson** [rspec/rspec-mocks#458]
Reproduce with the following:

``` ruby
   describe 'matches_name_but_not_args' do
     let(:client){ double('athing=' => true) }
     it "errors" do
       client.athing = 'mavis'
     end
   end
```

```
Backtrace: 

  1) matches_name_but_not_args errors
     Failure/Error: client.athing = 'mavis'
     NoMethodError:
       undefined method `matches_name_but_not_args' for #<RSpec::Mocks::SimpleMessageExpectation:0x007fdc5b126328>
     # /Users/paul/.rvm/gems/ruby-2.0.0-p195/gems/rspec-mocks-3.0.0.beta1/lib/rspec/mocks/proxy.rb:230:in `block in find_almost_matching_stub'
     # /Users/paul/.rvm/gems/ruby-2.0.0-p195/gems/rspec-mocks-3.0.0.beta1/lib/rspec/mocks/proxy.rb:230:in `each'
     # /Users/paul/.rvm/gems/ruby-2.0.0-p195/gems/rspec-mocks-3.0.0.beta1/lib/rspec/mocks/proxy.rb:230:in `find'
     # /Users/paul/.rvm/gems/ruby-2.0.0-p195/gems/rspec-mocks-3.0.0.beta1/lib/rspec/mocks/proxy.rb:230:in `find_almost_matching_stub'
     # /Users/paul/.rvm/gems/ruby-2.0.0-p195/gems/rspec-mocks-3.0.0.beta1/lib/rspec/mocks/proxy.rb:170:in `message_received'
     # /Users/paul/.rvm/gems/ruby-2.0.0-p195/gems/rspec-mocks-3.0.0.beta1/lib/rspec/mocks/method_double.rb:82:in `proxy_method_invoked'
     # /Users/paul/.rvm/gems/ruby-2.0.0-p195/gems/rspec-mocks-3.0.0.beta1/lib/rspec/mocks/method_double.rb:69:in `block (2 levels) in define_proxy_method'
```

Have fun :-)
