### ISSUE TITLE
Can't stub I18n.

### ISSUE THREAD

**Issue by Exoth** [rspec/rspec-mocks#663]
Let's have such specs:

```
describe 'the bug' do
  context 'with a stub' do
    before { I18n.stub(:locale).and_return(:de) }
    specify { I18n.locale.should == :de }
    specify { I18n.t('autocomplete.all_airports').should == 'Alle Flughäfen' }
  end

  context 'with a proc stub' do
    before { I18n.stub(:locale) { :de } }
    specify { I18n.locale.should == :de }
    specify { I18n.t('autocomplete.all_airports').should == 'Alle Flughäfen' }
  end

  context 'with an assignment' do
    before { I18n.locale = :de }
    specify { I18n.locale.should == :de }
    specify { I18n.t('autocomplete.all_airports').should == 'Alle Flughäfen' }
  end

end
```

The result is:

```
Failures:

  1) the bug with a stub should == "Alle Flughäfen"
     Failure/Error: specify { I18n.t('autocomplete.all_airports').should == 'Alle Flughäfen' }
       expected: "Alle Flughäfen"
            got: "All airports" (using ==)
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/matchers/operator_matcher.rb:56:in `fail_with_message'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/matchers/operator_matcher.rb:98:in `__delegate_operator'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/matchers/operator_matcher.rb:88:in `eval_match'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/matchers/operator_matcher.rb:37:in `block in use_custom_matcher_or_delegate'
     # ./spec/models/autocomplete_places_spec.rb:280:in `block (3 levels) in <top (required)>'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:114:in `instance_eval'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:114:in `block in run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:111:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:390:in `block in run_examples'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:386:in `map'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:386:in `run_examples'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:371:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `block in run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `map'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `map'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `block in run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:58:in `report'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:25:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'

  2) the bug with a proc stub should == "Alle Flughäfen"
     Failure/Error: specify { I18n.t('autocomplete.all_airports').should == 'Alle Flughäfen' }
       expected: "Alle Flughäfen"
            got: "All airports" (using ==)
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/matchers/operator_matcher.rb:56:in `fail_with_message'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/matchers/operator_matcher.rb:98:in `__delegate_operator'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/matchers/operator_matcher.rb:88:in `eval_match'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-expectations-2.14.5/lib/rspec/matchers/operator_matcher.rb:37:in `block in use_custom_matcher_or_delegate'
     # ./spec/models/autocomplete_places_spec.rb:286:in `block (3 levels) in <top (required)>'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:114:in `instance_eval'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:114:in `block in run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:111:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:390:in `block in run_examples'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:386:in `map'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:386:in `run_examples'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:371:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `block in run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `map'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `map'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `block in run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:58:in `report'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:25:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
     # /home/exoth/.rvm/gems/ruby-1.9.3-p545@jetradar/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
```

So both stubs failed to make I18n.t use the specified locale despite the fact, that I18n.locale gives the right locale.

I18n version is 0.6.9, rspec-mocks verion is 2.14.6.
