### ISSUE TITLE
Multi message expectation should show each allowed message

### ISSUE THREAD

**Issue by scotthain** [rspec/rspec-mocks#779]
The following is an example of some confusing output that could be cleared up.

```
describe "multi message expectation could be nicer" do
  let(:subject) { Object.new }

  it "should show each allowed message" do
    expect(subject).to receive(:foo).with("one")
    expect(subject).to receive(:foo).with("two")

    subject.foo("two+TYPO")
  end
end
```

The output is:

```
Failures:

  1) multi message expectation could be nicer should show each allowed message
     Failure/Error: subject.foo("two+TYPO")
       #<Object:0x007fb8ca9b8220> received :foo with unexpected arguments
         expected: ("one")
              got: ("two+TYPO")
     # ./spec/unit/tester_spec.rb:9:in `block (2 levels) in <top (required)>'
```

I would expect the output to describe the different allowed messages, to ease debugging. Thanks!
