### ISSUE TITLE
Message expectation unexpectedly failing when calling method with an object defining #==

### ISSUE THREAD

**Issue by carhartl** [rspec/rspec-mocks#914]
Using RSpec 3.2.2 given the following example code:

```ruby
class Foo
  attr_reader :a, :b

  def initialize(a:, b:)
    @a = a
    @b = b
  end
  
  def ==(other)
    a == other.a && b == other.b
  end
end

class Bar
  def do_something_with(foo)
    puts foo
  end
end


describe Bar do
  let(:foo) { Foo.new(a: "a", b: "b") }
  
  it "testing argument matcher" do
    expect_any_instance_of(Bar).to receive(:do_something_with)
    Bar.new.do_something_with(foo)
  end
end
```

I am seeing the example unexpectedly fail:

```
Failures:

  1) Bar testing argument matcher
     Failure/Error: a == other.a && b == other.b
     NoMethodError:
       undefined method `a' for #<RSpec::Mocks::ArgumentMatchers::AnyArgMatcher:0x007f8ad98c2768>
     # ./with_spec.rb:10:in `=='
     # ./with_spec.rb:26:in `block (2 levels) in <top (required)>'
```

As soon as I comment out `Foo#==` the spec will pass. Is this something I am doing wrong? Is it bad style/unexpected to redefine #==? I also tried to define my own argument matcher for foos in order to workaround this, but without luck.

I wasn't seeing this with an older version of RSpec.

**Comment by carhartl** [comment]
PS: I understood from the documentation, that "Arguments that are passed to with are compared with actual arguments received using ==", and even though `with` isn't even involved here, the any arguments matcher seems to be applied internally when omitting it?

**Comment by carhartl** [comment]
... and using an argument matcher explicitly is producing a similar error:

```ruby
it "testing argument matcher" do
  expect_any_instance_of(Bar).to receive(:do_something_with).with(kind_of(Foo))
  Bar.new.do_something_with(foo)
end
```

```
Failures:

  1) Bar testing argument matcher
     Failure/Error: a == other.a && b == other.b
     NoMethodError:
       undefined method `a' for #<RSpec::Mocks::ArgumentMatchers::KindOf:0x007f973c216760>
     # ./with_spec.rb:10:in `=='
     # ./with_spec.rb:26:in `block (2 levels) in <top (required)>'
```
