### ISSUE TITLE
Spies interact weirdly with failure aggregation

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-mocks#952]
``` ruby
RSpec.describe "Using spies with aggregate failures", :aggregate_failures do
  it "weirdly reports 3 failures" do
    my_spy = spy
    my_spy.foo(1)
    expect(my_spy).to have_received(:foo).with(2)
  end
end
```

This fails with an aggregated failure that lists 3 failures:

```
  1) Using spies with aggregate failures weirdly reports 3 failures
     Got 3 failures:

     1.1) Failure/Error: expect(my_spy).to have_received(:foo).with(2)
            #<Double (anonymous)> received :foo with unexpected arguments
              expected: (2)
                   got: (1)
          # /Users/myron/code/rspec-dev/repos/rspec-support/lib/rspec/support.rb:90:in `notify_failure'
          # ./lib/rspec/mocks/error_generator.rb:302:in `notify'
          # ./lib/rspec/mocks/error_generator.rb:298:in `__raise'
          # ./lib/rspec/mocks/error_generator.rb:53:in `raise_unexpected_message_args_error'
          # ./lib/rspec/mocks/proxy.rb:203:in `raise_unexpected_message_args_error'
          # ./lib/rspec/mocks/proxy.rb:109:in `check_for_unexpected_arguments'
          # ./lib/rspec/mocks/matchers/have_received.rb:99:in `generate_failure_message'
          # ./lib/rspec/mocks/matchers/have_received.rb:39:in `failure_message'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:35:in `handle_failure'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:27:in `with_matcher'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/expectation_target.rb:54:in `to'
          # ./spec/foo_spec.rb:5:in `block (2 levels) in <top (required)>'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:206:in `instance_exec'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:206:in `block in run'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:411:in `block in with_around_and_singleton_context_hooks'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:369:in `block in with_around_example_hooks'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:476:in `block in run'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:616:in `block in run_around_example_hooks_for'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'

     1.2) Failure/Error: expect(my_spy).to have_received(:foo).with(2)
            (Double (anonymous)).foo(2)
                expected: 1 time with arguments: (2)
                received: 0 times
          # /Users/myron/code/rspec-dev/repos/rspec-support/lib/rspec/support.rb:90:in `notify_failure'
          # ./lib/rspec/mocks/error_generator.rb:302:in `notify'
          # ./lib/rspec/mocks/error_generator.rb:298:in `__raise'
          # ./lib/rspec/mocks/error_generator.rb:83:in `raise_expectation_error'
          # ./lib/rspec/mocks/message_expectation.rb:479:in `generate_error'
          # ./lib/rspec/mocks/matchers/have_received.rb:100:in `generate_failure_message'
          # ./lib/rspec/mocks/matchers/have_received.rb:39:in `failure_message'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:35:in `handle_failure'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:27:in `with_matcher'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/expectation_target.rb:54:in `to'
          # ./spec/foo_spec.rb:5:in `block (2 levels) in <top (required)>'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:206:in `instance_exec'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:206:in `block in run'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:411:in `block in with_around_and_singleton_context_hooks'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:369:in `block in with_around_example_hooks'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:476:in `block in run'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:616:in `block in run_around_example_hooks_for'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'

     1.3) Failure/Error: expect(my_spy).to have_received(:foo).with(2)
            [#<RSpec::Mocks::MockExpectationError: #<Double (anonymous)> received :foo with unexpected arguments
              expected: (2)
                   got: (1)>, #<RSpec::Mocks::MockExpectationError: (Double (anonymous)).foo(2)
                expected: 1 time with arguments: (2)
                received: 0 times>, #<RSpec::Expectations::ExpectationNotMetError: [...]>]
          # /Users/myron/code/rspec-dev/repos/rspec-support/lib/rspec/support.rb:90:in `notify_failure'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/fail_with.rb:27:in `fail_with'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:40:in `handle_failure'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:27:in `with_matcher'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
          # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/expectation_target.rb:54:in `to'
          # ./spec/foo_spec.rb:5:in `block (2 levels) in <top (required)>'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:206:in `instance_exec'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:206:in `block in run'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:411:in `block in with_around_and_singleton_context_hooks'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:369:in `block in with_around_example_hooks'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:476:in `block in run'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:616:in `block in run_around_example_hooks_for'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'
          # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'
```

If you add another exception, it's weird in a different way:

``` ruby
RSpec.describe "Using spies with aggregate failures", :aggregate_failures do
  it "weirdly reports 3 failures" do
    my_spy = spy
    my_spy.foo(1)
    expect(my_spy).to have_received(:foo).with(2)

    boom
  end
end
```

```
  An error occurred in an `around(:example)` hook
    RSpec::Expectations::MultipleExpectationsNotMetError: Got 3 failures from failure aggregation block:

  1) #<Double (anonymous)> received :foo with unexpected arguments
       expected: (2)
            got: (1)

  2) (Double (anonymous)).foo(2)
         expected: 1 time with arguments: (2)
         received: 0 times

  3) [#<RSpec::Mocks::MockExpectationError: #<Double (anonymous)> received :foo with unexpected arguments
       expected: (2)
            got: (1)>, #<RSpec::Mocks::MockExpectationError: (Double (anonymous)).foo(2)
         expected: 1 time with arguments: (2)
         received: 0 times>, #<RSpec::Expectations::ExpectationNotMetError: [...]>]
    occurred at /Users/myron/code/rspec-dev/repos/rspec-support/lib/rspec/support.rb:90:in `call'

  weirdly reports 3 failures (FAILED - 1)

Failures:

  1) Using spies with aggregate failures weirdly reports 3 failures
     Failure/Error: boom
     NameError:
       undefined local variable or method `boom' for #<RSpec::ExampleGroups::UsingSpiesWithAggregateFailures:0x007ffefc009e90>
     # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/matchers.rb:966:in `method_missing'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:666:in `method_missing'
     # ./spec/foo_spec.rb:7:in `block (2 levels) in <top (required)>'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:206:in `instance_exec'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:206:in `block in run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:411:in `block in with_around_and_singleton_context_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:369:in `block in with_around_example_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:476:in `block in run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:616:in `block in run_around_example_hooks_for'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'
     # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/failure_aggregator.rb:10:in `block in aggregate'
     # /Users/myron/code/rspec-dev/repos/rspec-support/lib/rspec/support.rb:96:in `with_failure_notifier'
     # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/expectations/failure_aggregator.rb:8:in `aggregate'
     # /Users/myron/code/rspec-dev/repos/rspec-expectations/lib/rspec/matchers.rb:313:in `aggregate_failures'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1739:in `block in define_built_in_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:359:in `instance_exec'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:359:in `instance_exec'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:387:in `execute_with'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:618:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:273:in `call'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:619:in `run_around_example_hooks_for'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:476:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:369:in `with_around_example_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:411:in `with_around_and_singleton_context_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:203:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:554:in `block in run_examples'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:550:in `map'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:550:in `run_examples'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:516:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:115:in `map'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1620:in `with_suite_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/reporter.rb:70:in `report'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:113:in `run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:89:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:73:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:41:in `invoke'
     # /Users/myron/code/rspec-dev/repos/rspec-core/exe/rspec:4:in `<top (required)>'
     # ./bin/rspec:12:in `load'
     # ./bin/rspec:12:in `<main>'
```

Notice that in both these cases the 3rd failure is itself an array of failures. There are multiple oddities here.
